x-common-app-config: &common-app-config
  image: varlabz/linkedin-pw
  volumes:
    - ./data:/app/data
  env_file:
    - .key       
  restart: "no"
  network_mode: host        
  profiles:
    - final

x-common-app-config-dev: &common-app-config-dev
  build:
    target: dev
    dockerfile: dockerfile
  volumes:
    - ./:/app/
  env_file:
    - .key       
  restart: "no"
  network_mode: host        
  profiles:
    - dev

services:
# dev services     
  dev:
    <<: *common-app-config-dev       
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher-ignore", "66", "--matcher", "75", "--speed", "1", "--max-pages", "1000"]      

# prod services     
  urls:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher-ignore", "65", "--matcher", "75", "--speed", "1", "--max-pages", "1000"]      

  current:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher-ignore", "60", "--matcher", "70", "--speed", "1", "--max-pages", "1000", "--debug-no-url"] 

  25mi:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher-ignore", "65", "--matcher", "75", "--url", "https://www.linkedin.com/jobs/search/?distance=25&f_E=4%2C5&f_JT=F&f_TPR=r86400&geoId=106233382&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true&sortBy=R"]

  1-page:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--click-apply", "--click-easy-apply", "--matcher", "70", "--speed", "1", "--max-pages", "1"]      
    
  try:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--matcher", "70", "--speed", "0", "--debug-1page",]      

  job:
    <<: *common-app-config      
    environment:
      JOB: ${JOB:-''}
    command: ["python", "-u", "src/chat.py", "-j", "data/${JOB:-'create file with job description'}"]      

  help:
    <<: *common-app-config        
    command: ["python", "-u", "src/linkedin.py", "--help",]      
